### PR TITLE
add ordinary T stat into nfiti_ebayes

### PR DESCRIPTION
**Pull request by gwang37**

### CODE REVIEW

**Comment by muschellij2** [comment]
Can you resolve the conflicts?  It seems as though you didn't pull before making changes

**Comment by gwang37** [comment]
> Can you resolve the conflicts? It seems as though you didn't pull before making changes

>I tried to fix it. how about now?

**Comment by muschellij2** [comment]
FYI - @gwang37 I changed the name a bit to `standard_t_stat` rather than `Ordinary`

**Comment by gwang37** [comment]
Thanks! But I guess we should be consistent with the paper notations?
Martin, what do you think?

Best,
Guoqing

**Comment by gwang37** [comment]
I guess the question, is Student's t-test a "standard" or "ordinary"
measure?
Best,
John

**Comment by gwang37** [comment]
Standard is probably better to be honest. I think in the text the 'ordinary
least squares' and 'standard t-statistic' got a little mixed up, as they
are referring to the same thing in this context. That is probably my bad. I
can go back and change that.

On Mon, Sep 21, 2020 at 10:40 AM John Muschelli <muschellij2@gmail.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> I guess the question, is Student's t-test a "standard" or "ordinary"
> measure?
> Best,
> John
>
>
> On Mon, Sep 21, 2020 at 10:37 AM Guoqing Wang <gqwang1001@gmail.com>
> wrote:
>
>> Thanks! But I guess we should be consistent with the paper notations?
>> Martin, what do you think?
>>
>> Best,
>> Guoqing
>>
>> On Mon, Sep 21, 2020 at 10:26 AM John Muschelli <notifications@github.com>
>> wrote:
>>
>>> FYI - @gwang37
>>> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgwang37&data=02%7C01%7Cmlindquist%40jhu.edu%7C4845bb6db8704abe9ff608d85e3c5507%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637362960497066851&sdata=9yeOSkaVWVX%2FoYuJPuLjsNLoy1BIpTXHl0P1fcCSkTA%3D&reserved=0>
>>> I changed the name a bit to standard_t_stat rather than Ordinary
>>>
>>> —
>>> You are receiving this because you were mentioned.
>>> Reply to this email directly, view it on GitHub
>>> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmuschellij2%2Flimmi%2Fpull%2F3%23issuecomment-696151023&data=02%7C01%7Cmlindquist%40jhu.edu%7C4845bb6db8704abe9ff608d85e3c5507%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637362960497066851&sdata=cx0GK7D%2FJXtiwYR3iOvAb5HlAPhGbBIxNVav6ZiJzTw%3D&reserved=0>,
>>> or unsubscribe
>>> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADUAWLSJRKZZJMHHWGXSNGDSG5PABANCNFSM4RSZIBQA&data=02%7C01%7Cmlindquist%40jhu.edu%7C4845bb6db8704abe9ff608d85e3c5507%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637362960497076851&sdata=26GkO%2FK9XotwyFv30w2HE1yFFw6PFv7VxGwZRtHeKcU%3D&reserved=0>
>>> .
>>>
>>

-- 
Martin Lindquist
Professor
Department of Biostatistics
Johns Hopkins University
http://www.biostat.jhsph.edu/~mlindqui/

**Comment by gwang37** [comment]
I agree! I can help to change the notation in the paper and figures.

**Comment by gwang37** [comment]
Great, thanks!

On Mon, Sep 21, 2020 at 11:47 AM Guoqing Wang <gqwang1001@gmail.com> wrote:

>
> *      External Email - Use Caution      *
>
>
>
> I agree! I can help to change the notation in the paper and figures.
>
>
>
> On Mon, Sep 21, 2020 at 10:48 AM Martin Lindquist <mlindqui@jhsph.edu>
> wrote:
>
>> Standard is probably better to be honest. I think in the text the
>> 'ordinary least squares' and 'standard t-statistic' got a little mixed up,
>> as they are referring to the same thing in this context. That is probably
>> my bad. I can go back and change that.
>>
>> On Mon, Sep 21, 2020 at 10:40 AM John Muschelli <muschellij2@gmail.com>
>> wrote:
>>
>>>
>>> *      External Email - Use Caution      *
>>>
>>>
>>>
>>> I guess the question, is Student's t-test a "standard" or "ordinary"
>>> measure?
>>> Best,
>>> John
>>>
>>>
>>> On Mon, Sep 21, 2020 at 10:37 AM Guoqing Wang <gqwang1001@gmail.com>
>>> wrote:
>>>
>>>> Thanks! But I guess we should be consistent with the paper notations?
>>>> Martin, what do you think?
>>>>
>>>> Best,
>>>> Guoqing
>>>>
>>>> On Mon, Sep 21, 2020 at 10:26 AM John Muschelli <
>>>> notifications@github.com> wrote:
>>>>
>>>>> FYI - @gwang37
>>>>> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgwang37&data=02%7C01%7Cmlindquist%40jhu.edu%7C84344b58fcb94998a02508d85e45aee7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637363000658737907&sdata=J4KxZHZ8xGbzoj690fdd4TCVfA55zAX6RYKTl1ddA6w%3D&reserved=0>
>>>>> I changed the name a bit to standard_t_stat rather than Ordinary
>>>>>
>>>>> —
>>>>> You are receiving this because you were mentioned.
>>>>> Reply to this email directly, view it on GitHub
>>>>> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmuschellij2%2Flimmi%2Fpull%2F3%23issuecomment-696151023&data=02%7C01%7Cmlindquist%40jhu.edu%7C84344b58fcb94998a02508d85e45aee7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637363000658737907&sdata=r03vqCa2ncEfseadfEVNzr2lROLq4CWKyvVbqr5MgwY%3D&reserved=0>,
>>>>> or unsubscribe
>>>>> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADUAWLSJRKZZJMHHWGXSNGDSG5PABANCNFSM4RSZIBQA&data=02%7C01%7Cmlindquist%40jhu.edu%7C84344b58fcb94998a02508d85e45aee7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637363000658747900&sdata=1PcR%2FpBI4y892Jya96p16Y7OHemkZaJk4alizd2K4XU%3D&reserved=0>
>>>>> .
>>>>>
>>>>
>>
>> --
>> Martin Lindquist
>> Professor
>> Department of Biostatistics
>> Johns Hopkins University
>> http://www.biostat.jhsph.edu/~mlindqui/
>> <https://nam02.safelinks.protection.outlook.com/?url=http:%2F%2Fwww.biostat.jhsph.edu%2F~mlindqui%2F&data=02%7C01%7Cmlindquist%40jhu.edu%7C84344b58fcb94998a02508d85e45aee7%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637363000658747900&sdata=mBIa8c3znVhPWO1DbaUfc1jw9Ze%2Fpp8XXAMRn6ynqMs%3D&reserved=0>
>>
>

-- 
Martin Lindquist
Professor
Department of Biostatistics
Johns Hopkins University
http://www.biostat.jhsph.edu/~mlindqui/

**Pull request merged**
